server:
  port: 1111

spring:
  autoconfigure:
    exclude: org.redisson.spring.starter.RedissonAutoConfiguration
  redis:
    database: 0
    host: 192.168.17.131
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 2
      shutdown-timeout: 100ms